app_web:
    resource: '@AppBundle/Controller/Web'
    type: annotation

app_api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
    defaults:
        _format: json



fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path: /
    defaults:
        _controller: AppBundle:Web\Main:homepage
